name: 'User config'
description: 'User config'
inputs:
  user-from:
    type: choice
    description: 'The user owner'
    required: true
    default: 'github-bot'
    options:
      - 'app-bot'
      - 'github-bot'
      - 'commit-head'
  app-id: 
    type: string
    description: 'The app id'
    required: inputs.user-from == 'app-bot'
  app-private-key: 
    type: string
    description: 'The app private key'
    required: inputs.user-from == 'app-bot'
runs:
  using: "composite"
  steps:
    - name: Set GitHub Path
      run: echo "$GITHUB_ACTION_PATH" >> $GITHUB_PATH
      shell: bash
      env:
        GITHUB_ACTION_PATH: ${{ github.action_path }}

    - uses: actions/create-github-app-token@v1
      id: app-token
      if: ${{ inputs.user-from == 'app-bot' }}
      with:
        app-id: ${{ inputs.app-id }}
        private-key: ${{ inputs.app-private-key }}
    
    - name: Get git
      id: get-user-id
      if: ${{ inputs.user-from == 'app-bot' }}
      run: echo "user-id=$(gh api "/users/${{ steps.app-token.outputs.app-slug }}[bot]" --jq .id)" >> "$GITHUB_OUTPUT"
      env:
        GH_TOKEN: ${{ steps.app-token.outputs.token }}

    - name: Config git name and email
      run: set-config-user.sh "$USER_FROM" "$APP_SLUG" "$USER_ID"
      shell: bash
      env:
        USER_FROM: ${{ inputs.user-from }}
        APP_SLUG: ${{ steps.app-token.outputs.app-slug }}
        USER_ID: ${{ steps.get-user-id.outputs.user-id }}

