name: 'User config'
description: 'User config'
inputs:
  user-from:
    type: choice
    description: 'The user owner'
    required: true
    default: 'github-bot'
    options:
      - 'github-bot'
      - 'commit-head'
      - 'custom'
  user-name: 
    type: string
    description: 'The user name'
  user-email: 
    type: string
    description: 'The user email'
runs:
  using: "composite"
  steps:
    - name: Set GitHub Path
      run: echo "$GITHUB_ACTION_PATH" >> $GITHUB_PATH
      shell: bash
      env:
        GITHUB_ACTION_PATH: ${{ github.action_path }}

    - name: Config git name and email
      run: set-config-user.sh "$USER_FROM" "$USER_NAME" "$USER_EMAIL"
      shell: bash
      env:
        USER_FROM: ${{ inputs.user-from }}
        USER_NAME: ${{ inputs.user-name }}
        USER_EMAIL: ${{ inputs.user-email }}

