name: 'User config'
description: 'User config'
inputs:
  user-from:
    type: choice
    description: 'The user owner'
    required: true
    default: 'github-bot'
    options:
      - 'app-bot'
      - 'github-bot'
      - 'commit-head'
  app-slug: 
    type: string
    description: 'The app id'
    required: inputs.user-from == 'app-bot'
  user-id: 
    type: string
    description: 'The user id'
    required: inputs.user-from == 'app-bot'
runs:
  using: "composite"
  steps:
    - name: Set GitHub Path
      run: echo "$GITHUB_ACTION_PATH" >> $GITHUB_PATH
      shell: bash
      env:
        GITHUB_ACTION_PATH: ${{ github.action_path }}
    
    - name: Config git name and email
      run: set-config-user.sh "$USER_FROM" "$APP_SLUG" "$USER_ID"
      shell: bash
      env:
        APP_SLUG: ${{ inputs.app-slug }}
        USER_FROM: ${{ inputs.user-from }}
        USER_ID: ${{ inputs.user-id }}

