name: 'Create Tag'
description: 'Create tag'
inputs:
  tag-message:
    description: 'Tag message'
    default: 'New version %s\n\n Log changes: \n\n%s'
  current-version:
    description: 'Current version'
    required: true
  commit-list:
    description: 'List of commits to compute'
    required: false
  commit-list-sep:
    description: 'The list separator'
    required: true
    default: ':::'
runs:
  using: "composite"
  steps:
    - name: Set GitHub Path
      run: echo "$GITHUB_ACTION_PATH" >> $GITHUB_PATH
      shell: bash
      env:
        GITHUB_ACTION_PATH: ${{ github.action_path }}

    - name: Create the tag
      run: create-tag.sh "$CURRENT_VERSION" "$TAG_MESSAGE" "$COMMIT_LIST" "$COMMIT_LIST_SEP"
      shell: bash
      env:
        TAG_MESSAGE: ${{ inputs.tag-message }}
        COMMIT_LIST: ${{ inputs.commit-list }}
        COMMIT_LIST_SEP: ${{ inputs.commit-list-sep }}
        CURRENT_VERSION: ${{ inputs.current-version }}

