#!/bin/bash

NEW_VERSION=$1
TAG_MESSAGE=$2
COMMIT_LIST=$3
COMMIT_LIST_SEP=$4
COMMIT_MESSAGE=$(printf "${TAG_MESSAGE}" "${NEW_VERSION}" "${COMMIT_LIST//$COMMIT_LIST_SEP//$'\n'}")

echo "COMMIT_MESSAGE: ${NEW_VERSION}" >&2

git tag -a "v${NEW_VERSION}" -m "${MESSAGE}"
git push origin tag "v${NEW_VERSION}"
