name: 'Tag commit'
description: 'Tag commit'
inputs:
  commit-from:
    description: 'The commit to start search from'
    required: true
  commit-format:
    description: 'The commit format list'
    required: true
    default: "%h %s - %ae"
outputs:
  commit-list:
    description: "List of commits"
    value: ${{ steps.commit-list.outputs.commit-list}}
runs:
  using: "composite"
  steps:
    - name: Set GitHub Path
      run: echo "$GITHUB_ACTION_PATH" >> $GITHUB_PATH
      shell: bash
      env:
        GITHUB_ACTION_PATH: ${{ github.action_path }}

    - name: Get commit list
      id: commit-list
      run: echo "commit-list=$(get-commit-list.sh $FROM $FORMAT)" >> $GITHUB_OUTPUT
      shell: bash
      env:
        FROM: ${{ inputs.commit-from }}
        FORMAT: ${{ inputs.commit-format }}
