#!/bin/bash

COMMIT_FROM=$1
COMMIT_FORMAT=$2
COMMIT_LIST_SEP=$3

COMMIT_LIST=$(git log $COMMIT_FROM..HEAD --format="${COMMIT_FORMAT}" --reverse)

echo "COMMIT_FORMAT: ${COMMIT_FORMAT}" >&2
echo "COMMIT_LIST_SEP: ${COMMIT_LIST_SEP}" >&2

OLDIFS="$IFS"
IFS=$'\n'
for COMMIT in ${COMMIT_LIST}; do
  echo "COMMIT: ${COMMIT}" >&2
done
IFS="$OLDIFS"

echo "${COMMIT_LIST//$'\n'/$COMMIT_LIST_SEP}"