name: 'Update version'
description: 'Update version'
inputs:
  commit-message:
    description: 'Update message'
    default: 'chore(build): bump version to v%s'
  new-version:
    description: 'New version'
    required: true
runs:
  using: "composite"
  steps:
    - name: Set GitHub Path
      run: echo "$GITHUB_ACTION_PATH" >> $GITHUB_PATH
      shell: bash
      env:
        GITHUB_ACTION_PATH: ${{ github.action_path }}

    - name: Update version
      run: update-version.sh "$NEW_VERSION" "$COMMIT_MESSAGE"
      shell: bash
      env:
        NEW_VERSION: ${{ inputs.new-version }}
        COMMIT_MESSAGE: ${{ inputs.commit-message }}