name: 'Current version'
description: 'Current version'
inputs:
  package-name: 
    description: 'The package name'
  default-version:
    description: 'Default version. Default value for version-from[git | current]'
    required: true
  version-from:
    type: choice
    description: 'The type of the version'
    required: true
    default: git
    options:
      - git
      - current
outputs:
  version:
    description: "Resolved version"
    value: ${{ steps.get-current-version.outputs.current-version }}
runs:
  using: "composite"
  steps:
    - name: Set GitHub Path
      run: echo "$GITHUB_ACTION_PATH" >> $GITHUB_PATH
      shell: bash
      env:
        GITHUB_ACTION_PATH: ${{ github.action_path }}

    - name: Get current version
      id: get-current-version 
      run: echo "current-version=$(get-current-version.sh "$VERSION_FROM" "$DEFAULT_VERSION" "$PACKAGE_NAME")" >> $GITHUB_OUTPUT
      shell: bash
      env:
        DEFAULT_VERSION: ${{ inputs.default-version }}
        VERSION_FROM: ${{ inputs.version-from }}
        PACKAGE_NAME: ${{ inputs.package-name }}